package io.microorm.schema;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatCode;

import io.microorm.metadata.EntityMetadata;
import io.microorm.metadata.MetadataRegistry;
import io.microorm.support.TestEntities;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import io.microorm.example.User;
import io.microorm.example.Order;

class SchemaExporterTest {

    private final MetadataRegistry registry = new MetadataRegistry();
    private final SchemaExporter exporter = new SchemaExporter(registry);

    private EntityMetadata user() {
        return registry.metadataFor(User.class);
    }

    private EntityMetadata order() {
        return registry.metadataFor(Order.class);
    }

    @Test
    @DisplayName("CREATE TABLE contains every mapped column with its SQL type and nullability")
    void createsTable() {
        String ddl = new DdlGenerator(registry).createTableStatement(user());

        assertThat(ddl).isEqualTo("""
                CREATE TABLE users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email VARCHAR(255) NOT NULL,
                    name VARCHAR(255),
                    age INTEGER,
                    active BOOLEAN,
                    bio TEXT,
                    created_at TIMESTAMP,
                    version INTEGER NOT NULL DEFAULT 0
                )""");
    }

    @Test
    @DisplayName("assigned identifiers are plain NOT NULL primary keys")
    void createsTableWithAssignedIdentifier() {
        String ddl = new DdlGenerator(registry).createTableStatement(registry.metadataFor(TestEntities.AuditEvent.class));

        assertThat(ddl).startsWith("CREATE TABLE audit_events (\n    id UUID NOT NULL PRIMARY KEY,");
    }

    @Test
    @DisplayName("sequence-based identifiers get a CREATE SEQUENCE and a nextval default")
    void createsSequence() {
        DdlGenerator generator = new DdlGenerator(registry);

        assertThat(generator.sequenceName(order())).contains("orders_id_seq");
        assertThat(generator.sequenceName(user())).isEmpty();
        assertThat(generator.createTableStatement(order())).contains("DEFAULT nextval('orders_id_seq')");
    }

    @Test
    @DisplayName("associations become foreign keys pointing at the referenced table")
    void createsForeignKeys() {
        List<String> statements = new DdlGenerator(registry).createSchemaStatements(List.of(user(), order()));

        assertThat(statements).contains(
                "ALTER TABLE orders ADD CONSTRAINT fk_orders_user_id FOREIGN KEY (user_id) REFERENCES users (id)");
    }

    @Test
    @DisplayName("references to classes that are not entities are skipped")
    void skipsUnknownForeignKeyTargets() {
        EntityMetadata metadata = registry.metadataFor(TestEntities.OrderOfNonEntity.class);

        List<String> statements = new DdlGenerator(registry).createSchemaStatements(List.of(metadata));

        assertThat(statements).noneMatch(statement -> statement.contains("FOREIGN KEY"));
        assertThat(new DdlGenerator(registry).createTableStatement(metadata)).contains("\n    user_id BIGINT\n)");
    }

    @Test
    @DisplayName("the script is ordered sequences, tables, foreign keys and terminated by semicolons")
    void scriptIsExecutableOrder() {
        String script = exporter.script(List.of(order(), user()));

        assertThat(script).startsWith("-- Generated by MicroORM SchemaExporter.");
        List<String> statements = script.lines().filter(line -> line.startsWith("CREATE")).toList();
        assertThat(statements).containsExactly(
                "CREATE SEQUENCE IF NOT EXISTS orders_id_seq;",
                "CREATE TABLE orders (",
                "CREATE TABLE users (");
        assertThat(script).endsWith(";\n");
        assertThat(script).contains("ALTER TABLE orders ADD CONSTRAINT fk_orders_user_id");
    }

    @Test
    @DisplayName("writes the script to a file")
    void exportsToFile(@TempDir Path directory) throws IOException {
        Path target = directory.resolve("nested/schema.sql");

        Path written = exporter.exportToFile(List.of(user()), target);

        assertThat(written).exists();
        assertThat(Files.readString(written)).contains("CREATE TABLE users (").endsWith(";\n");
    }

    @Test
    @DisplayName("scriptFor resolves entity classes through the registry")
    void exportsByClass() {
        assertThat(exporter.scriptFor(registry, User.class)).contains("CREATE TABLE users (");
    }

    @Test
    @DisplayName("console export never fails")
    void exportsToConsole() {
        assertThatCode(() -> exporter.exportToConsole(List.of(user()))).doesNotThrowAnyException();
    }
}