package io.microorm.sql;

import java.util.List;
import java.util.Optional;

/**
 * {@code INSERT INTO table (columns) VALUES (?, ...)}, optionally with a {@code RETURNING} clause.
 *
 * @param sql              SQL text
 * @param parameters       bind parameters in placeholder order
 * @param returningColumn  column to read back with {@code RETURNING}, empty when the identifier
 *                         was generated by a sequence and is therefore known in advance
 */
public record InsertStatement(String sql, List<Bind> parameters, Optional<String> returningColumn)
        implements SqlStatement {

    public InsertStatement {
        parameters = List.copyOf(parameters);
    }

    /** @return {@code true} when the generated identifier has to be read back from the database */
    public boolean returnsGeneratedKeys() {
        return returningColumn.isPresent();
    }
}
