package io.microorm.id;

import io.microorm.metadata.EntityMetadata;
import java.sql.Connection;
import java.util.Optional;

/**
 * Relies on an identity column: the database assigns the value.
 *
 * <p>MicroORM never calls {@code getGeneratedKeys()}; the {@code RETURNING} clause generated by
 * {@link io.microorm.sql.SqlGenerator} is explicit SQL, so the behaviour does not depend on how a
 * particular driver emulates generated keys.
 */
public final class IdentityIdGenerator implements IdGenerator {

    @Override
    public Optional<Object> generate(Connection connection, EntityMetadata entity) {
        return Optional.empty();
    }
}
