package io.microorm.annotation;

import java.lang.annotation.Documented;
import java.lang.annotation.ElementType;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;
import java.lang.annotation.Target;

/**
 * Declares that the identifier is generated by the database rather than by the application.
 *
 * <p>May only be used together with {@link Id}. Non-annotated identifiers must be assigned by
 * the application before {@code persist}.
 */
@Documented
@Retention(RetentionPolicy.RUNTIME)
@Target(ElementType.FIELD)
public @interface GeneratedValue {

    /** @return generation strategy */
    GenerationType strategy() default GenerationType.AUTO;
}
