package io.microorm.annotation;

/** Identifier generation strategies, implemented by {@code io.microorm.id.IdGenerator} implementations. */
public enum GenerationType {

    /**
     * Asks {@code AutoIdGenerator} to inspect {@link java.sql.DatabaseMetaData}: when a sequence named
     * {@code <table>_id_seq} exists it is used, otherwise the identity column of the table is used.
     */
    AUTO,

    /** Relies on {@code GENERATED BY DEFAULT AS IDENTITY} / {@code BIGSERIAL} and reads back generated keys. */
    IDENTITY,

    /** Reads the next value of sequence {@code <table>_id_seq} with {@code nextval('...')}. */
    SEQUENCE
}
