package io.microorm.schema;

import io.microorm.metadata.EntityMetadata;
import io.microorm.metadata.MetadataRegistry;
import java.io.IOException;
import java.io.UncheckedIOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collection;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Prints or writes the DDL that {@link DdlGenerator} derives from entity metadata.
 *
 * <p>This is a developer convenience, not a migration tool: the integration tests create their schema
 * from an explicit SQL file, and production schemas are expected to be owned by a migration tool.
 * Using generated DDL in production is exactly the mistake this class makes easy, hence the javadoc.
 *
 * <p>Console output is the one place where MicroORM writes to {@code System.out} instead of SLF4J,
 * because the output is the product here, not a diagnostic.
 */
public final class SchemaExporter {

    private static final Logger log = LoggerFactory.getLogger(SchemaExporter.class);

    private static final String HEADER = """
            -- Generated by MicroORM SchemaExporter.
            -- Statements are ordered: sequences, then tables, then foreign keys.
            """.stripTrailing();

    private final DdlGenerator generator;

    public SchemaExporter(MetadataRegistry registry) {
        this(new DdlGenerator(registry));
    }

    public SchemaExporter(DdlGenerator generator) {
        this.generator = generator;
    }

    /**
     * Renders the schema of the given entities as a single script.
     *
     * @param entities entities to export
     * @return the script, statements terminated by {@code ;}
     */
    public String script(Collection<EntityMetadata> entities) {
        StringBuilder out = new StringBuilder(HEADER).append("\n\n");
        generator.createSchemaStatements(entities)
                .forEach(statement -> out.append(statement).append(";\n"));
        return out.toString();
    }

    /**
     * Writes the schema to standard output.
     *
     * @param entities entities to export
     */
    public void exportToConsole(Collection<EntityMetadata> entities) {
        String script = script(entities);
        log.info("Exporting schema for {} entities", entities.size());
        System.out.println(script);
    }

    /**
     * Writes the schema to a file, creating parent directories when needed.
     *
     * @param entities entities to export
     * @param target   destination file
     * @return the written file
     * @throws UncheckedIOException when the file cannot be written
     */
    public Path exportToFile(Collection<EntityMetadata> entities, Path target) {
        try {
            Path parent = target.toAbsolutePath().getParent();
            if (parent != null) {
                Files.createDirectories(parent);
            }
            Files.writeString(target, script(entities), StandardCharsets.UTF_8);
        } catch (IOException e) {
            throw new UncheckedIOException("Cannot write schema to " + target, e);
        }
        log.info("Schema of {} entities written to {}", entities.size(), target);
        return target;
    }

    /**
     * Convenience overload for a registry lookup by class.
     *
     * @param registry metadata registry used to resolve the classes
     * @param types    entity classes
     * @return the script
     */
    public String scriptFor(MetadataRegistry registry, Class<?>... types) {
        List<EntityMetadata> metadata = registry.register(types);
        return script(metadata);
    }
}