package io.microorm.session;

import static org.assertj.core.api.Assertions.assertThat;

import io.microorm.example.User;
import io.microorm.pool.PoolConfig;
import io.microorm.query.SortDirection;
import io.microorm.support.FakeJdbc;
import java.util.List;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

/**
 * Executes the exact sequence shown in the README quick start.
 *
 * <p>A README that drifts from the code is worse than no README, so the example is compiled and run
 * here: the only difference is that the data source is the scripted JDBC fake instead of a PostgreSQL
 * container, because the API being demonstrated - not the driver - is what has to keep working.
 */
class ReadmeExampleTest {

    private static final String SELECT = "SELECT id, email, name, age, active, bio, created_at, version "
            + "FROM users";
    private static final String SELECT_BY_ID = SELECT + " WHERE id = ?";

    private final FakeJdbc database = new FakeJdbc();

    @Test
    @DisplayName("the quick start from the README works end to end")
    void quickStartFromReadme() {
        // 1./2. the factory, wired to a data source and a pool
        // The database assigns the identifier, so the INSERT reads it back with RETURNING.
        database.onQuery("INSERT INTO users (email, name, age, active, bio, version) "
                + "VALUES (?, ?, ?, ?, ?, ?) RETURNING id", 1L);

        SessionFactory factory = SessionFactory.builder()
                .connectionPool(database.dataSource(), PoolConfig.builder().minSize(2).maxSize(8).build())
                .entities(User.class)
                .build();

        // 3./4. persist in a transaction, then find by id
        User saved;
        try (Session session = factory.openSession()) {
            session.beginTransaction();
            saved = new User("ann@example.com", "Ann", 30, true);
            session.persist(saved);
            session.commit();
        }
        assertThat(saved.getId()).isNotNull();

        database.onQuery(SELECT_BY_ID, 1L, "ann@example.com", "Ann", 30, true, null, null, 0);
        database.onUpdate("UPDATE users SET name = ?, version = ? WHERE id = ? AND version = ?", 1);
        database.onQueries(SELECT + " WHERE age > ? AND active = ? ORDER BY name ASC LIMIT 10",
                List.<Object[]>of(new Object[]{1L, "ann@example.com", "Anna", 30, true, null, null, 1}));

        try (Session session = factory.openSession()) {
            User ann = session.findOrThrow(User.class, 1L);          // 5. find
            ann.setName("Anna");                                      // 6. change one field

            session.beginTransaction();
            session.commit();                                         // 7. UPDATE only name + version

            List<User> adults = session.createQuery(User.class)      // 8. fluent query
                    .where("age", ">", 18)
                    .and("active", "=", true)
                    .orderBy("name", SortDirection.ASC)
                    .limit(10)
                    .list();

            assertThat(ann.getName()).isEqualTo("Anna");
            assertThat(ann.getVersion()).isEqualTo(1);
            assertThat(adults).extracting(User::getName).containsExactly("Anna");
        }

        assertThat(database.statement("UPDATE users").orElseThrow().sql())
                .isEqualTo("UPDATE users SET name = ?, version = ? WHERE id = ? AND version = ?");

        // 9. the schema exporter renders DDL for the registered entities
        assertThat(factory.schemaExporter().script(factory.knownEntities()))
                .contains("CREATE TABLE users (")
                .contains("id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY");
    }
}